### ISSUE TITLE
Telegram bot для парсинга поисковой выдачи YouTube

### ISSUE THREAD

**Issue by kardinalanna** [SemenMartynov/Software-Engineering-2022#102]
Student, group: Карандина Анна, 90202
URL: https://github.com/kardinalanna/Software-Engineering.git
Git approach: git-flow

**Comment by SemenMartynov** [comment]
https://github.com/kardinalanna/Software-Engineering/network
(желательно, называть `feature`-ветки по принципу `feature/blah-blah-blah`)

`feature1` -- форкнута в от initial, который часть `develop` (так что ок) и потом была замерджена в `develop`. Тут всё норм.
`feature2` из `develop` и обратно в `develop`.
`feature3` форкнута от коммита в `feature2`, что не ОК, но иногда допускается, и обратно слита в `develop`.
Дальше рисунок становится сложнее...
`feature4` форкнута от `develop`, но от старого коммита, т.е. там нет изменений, которые были сделаны в `feature2` и `feature3`... И эти изменения были доставлены в `feature4` отдельным синком с `develop`. Потом изменения вернулись в `develop`, хорошо.
Дальше от `develop` форкнулся `release1`, там были сделаны изменения, но они не были возвращены в `develop`.
Потом от старого состояния `develop` появилась ветка `release2`, которая не учитывает многих изменений, и в неё полетели синки...
Все эти проблемы от того, что мерджи делали на одном хосте (на сервере ГитХаба, чере веб-интерфейс), а коммиты с разработкой на локальной машине, при этом `git pull` после мерджа не выполнялся (`HEAD` ветки не двигался).

Сейчас нужно удалить два последних коммита в `master`, и сделать нормальный `release/` из `develop`.

**Comment by kardinalanna** [comment]
Поняла свою ошибку
Откатилась в main и сделал новый release/1
Изменения в release/1  возвращены в develop

**Comment by SemenMartynov** [comment]
Не очень красивый граф по итогу получился, но, по крайней мере, и `master` и `develop` разлядеть можно
https://github.com/kardinalanna/Software-Engineering/network
