### ISSUE TITLE
TASK 2

### ISSUE THREAD

**Issue by Luciferuz** [SemenMartynov/Software-Engineering-2022#105]
Student, group: Antsiferov Sergey 3530901/90201
URL: https://github.com/Luciferuz/WebAppConverter
Git approach: Git-flow

**Comment by SemenMartynov** [comment]
`feaure`-ветки форкаются от `develop`, а не из последнего коммита предыдущей `feature`-ветки.
Смазанный какой-то `release` получился... Но может в 3-м задании получится лучше.
