### ISSUE TITLE
Telegram notes service

### ISSUE THREAD

**Issue by NoGe4Ek** [SemenMartynov/Software-Engineering-2022#11]
Student, group: Timofeev Kirill A., 3530901/90203
URL: https://github.com/NoGe4Ek/telegram-notes-service
Git approach: git-flow

**Comment by SemenMartynov** [comment]
no name has been provided

**Comment by NoGe4Ek** [comment]
> no name has been provided

fixed

**Comment by SemenMartynov** [comment]
Okay!
