### ISSUE TITLE
SoundCloud-Telegram_Bot

### ISSUE THREAD

**Issue by 11-kt** [SemenMartynov/Software-Engineering-2022#115]
Student, group:  Андрианов Виталий, 3530901/90202
URL: https://github.com/11-kt/SoundCloud-Telegram_Bot
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Не нужно лениться писать описания к комитам
https://github.com/11-kt/SoundCloud-Telegram_Bot/commits/main

**Comment by 11-kt** [comment]
Описания к комитам есть. 
Просто написаны через перенос строки, поэтому не отображаются
