### ISSUE TITLE
Degree , minute seconds converte

### ISSUE THREAD

**Issue by igalaxy00** [SemenMartynov/Software-Engineering-2022#124]
Student, group: Галактионов Игорь
URL: https://github.com/igalaxy00/Converter
Git approach: git-flow

**Comment by igalaxy00** [comment]
В графе есть 1 нюанс . В самом конце пришлось исправлять проблему с пермишенами для gradlew, а потом с тем же багом и той же веткой создавать новые пулреквесты, чтобы пофиксить ошибки сборки на github.
![image](https://user-images.githubusercontent.com/54952611/206228809-75502c6a-be55-4194-9879-f4c81cbf7434.png)

**Comment by SemenMartynov** [comment]
`+
