### ISSUE TITLE
Celsius-Fahrenheit Converter

### ISSUE THREAD

**Issue by k1eden** [SemenMartynov/Software-Engineering-2022#128]
Student, group: Beglaryan Garik, 3530901/90101
URL:  https://github.com/k1eden/Celsius-Fahrenheit
Git approach: git-flow

**Comment by k1eden** [comment]
Во время выполнения 2 лабораторной забыл, что нужно связывать issue с коммитами, поискал как можно добавить их на уже существующие коммиты, но побоялся что-нибудь испортить, если подскажете как это можно сделать безопасно - буду рад, а так в 3 работе постарался исправится!

**Comment by SemenMartynov** [comment]
Можно сделать новую ветку, через `cherry-pick` выдернуть в неё нужные коммиты, а потом через `--amend` отредактировать сообщение.
Ещё, думаю, это возможно через `git rebase -i`. Я так не делал, но вроде это возможно.
А вот третью работу не стоило начинать, до завернешния второй -- сейчас придётся больше коммитов перекидывать)

**Comment by k1eden** [comment]
Можно же просто в main и dev ветках сделать rebase интерактивный и изменить там названия?

**Comment by SemenMartynov** [comment]
Ну вот я и говорил выше, про `rebase -i`...
По идее, на выходе должен получиться новый `main` и новый `develop`. Рисунок коммитов должен сохраниться прежний (т.е. никаких прямых коммитов) но сами коммиты (по их sha) будут другими. Я так делал но с `cherry-pick`.

**Comment by k1eden** [comment]
Понял, сейчас попробую!

**Comment by SemenMartynov** [comment]
Если ничего не получится -- это не критично, но было бы здорово, если бы получилось)

**Comment by k1eden** [comment]
@SemenMartynov Сделал тестовую ветку, дабы проверить на всякий случай как все таки rebase сработает, история осталась такой же, за исключением того, что из нее пропали Merge requestы, это норм или я сделал что-то не так?) (Но слинковать все-таки получилось) 
![image](https://user-images.githubusercontent.com/54855506/206860959-ca5adfb1-efc5-496e-aac0-42ac884a073d.png)

**Comment by SemenMartynov** [comment]
Да, выглядит страшненько))
Похоже, только чери-пиками переносить.
Но ладно, пусть будет как есть (в смысле как было раньше).
Можно переходить к автотестам.

**Comment by k1eden** [comment]
Автотесты уже готовы, вроде как)
