### ISSUE TITLE
NoSQL Database

### ISSUE THREAD

**Issue by VladislavFetisov** [SemenMartynov/Software-Engineering-2022#129]
Student, group: Fetisov Vladislav 3530901/90202
URL: https://github.com/VladislavFetisov/NoSQL_DB
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Мы договаривались, что мерджи будут `--no-ff`. Сейчас, когда ты смотришь `blame` по `master`, нельзя понять в связи с какой задачей добавлена та или иная строчка.

В Docker нужно сделать отдельный стейдж для сборки, и отдельный для запуска.

**Comment by VladislavFetisov** [comment]
> Мы договаривались, что мерджи будут `--no-ff`. Сейчас, когда ты смотришь `blame` по `master`, нельзя понять в связи с какой задачей добавлена та или иная строчка.
> 
> В Docker нужно сделать отдельный стейдж для сборки, и отдельный для запуска.

FIXED

**Comment by VladislavFetisov** [comment]
> Настроить `.gitconfig`. Сейчас часть коммитов от "VladislavFetisov", а часть от "vladislav" ![image](https://user-images.githubusercontent.com/1230054/207120306-82c586c7-228c-4b23-8acb-8050fdf12537.png)

FIXED
