### ISSUE TITLE
OBJ-viewer

### ISSUE THREAD

**Issue by vasilievan** [SemenMartynov/Software-Engineering-2022#144]
Student, group: Васильев Алексей, 3530901/90203
URL: https://github.com/vasilievan/software_engineering
Git approach: git-flow

**Comment by SemenMartynov** [comment]
`feature\` ветка каждый раз форкается от `develop`, перед этим нужно делать `pull`.
Сейчас это выглядит так, будто каждая новая `feature\`-ветка пораждена из старой...
