### ISSUE TITLE
Celsius-Fahrenheit converter, part 3

### ISSUE THREAD

**Issue by k1eden** [SemenMartynov/Software-Engineering-2022#146]
Student, group: Beglaryan Garik, 3530901/90101
URL: https://github.com/k1eden/Celsius-Fahrenheit
Git approach: git-flow

**Comment by SemenMartynov** [comment]
`.idea/` нужно спрятать за `.gitignore`

Файл `build/libs/Celsius-Fahrenheit-1.0-SNAPSHOT.jar` есть только на твоём компе, в репо его нет (естественно). Бинарник должен собираться внутри Docker. Причём в одном контейнере собираться, а в другом запускаться.

**Comment by k1eden** [comment]
@SemenMartynov Fixed 👍

**Comment by k1eden** [comment]
Да, я что-то совсем рассеянный стал, неправильно было реализовано копирование `COPY build/libs/Celsius-Fahrenheit-1.0-SNAPSHOT.jar /app.jar`, а также уже позже нашел еще конфликт версий jdk и их тоже, вроде как, устранил.
В общем, надеюсь, что Fixed ))

**Comment by SemenMartynov** [comment]
`+
