### ISSUE TITLE
Telegram IMDB bot

### ISSUE THREAD

**Issue by Eugenepolyt** [SemenMartynov/Software-Engineering-2022#158]
Student, group: Борисов Евгений, 3530901/90201
URL: https://github.com/Eugenepolyt/-Software-Engineering-2022
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Коммиты не слинкованы с issues, а issues всё ещё открыты.

Последние изменения из `release/` и `hotfix/` не возвращены в `develop`.

Давай в `Dockerfile` сразу использовать официальный образ Python, чтоб сэкономить на количестве слоёв.

**Comment by Eugenepolyt** [comment]
> Коммиты не слинкованы с issues, а issues всё ещё открыты.
> 
> Последние изменения из `release/` и `hotfix/` не возвращены в `develop`.
> 
> Давай в `Dockerfile` сразу использовать официальный образ Python, чтоб сэкономить на количестве слоёв.

Связал ПР-ы с issues, перенес изменения из веток release, hotfix, подкорректировал докерфайл, сделал сборку на основе официального образа python

**Comment by SemenMartynov** [comment]
`+
