### ISSUE TITLE
morse

### ISSUE THREAD

**Issue by semwai** [SemenMartynov/Software-Engineering-2022#162]
Student, group: Shahbazov Elvin, 3530901/90201
URL: https://github.com/semwai/morse
Git approach: git-flow

**Comment by SemenMartynov** [comment]
`master` это долгоживущая ветка, её нельзя мерджить в develop
https://github.com/semwai/morse/commit/6732dc18ef06f38a1eb88cf4a075972e959751e8

**Comment by semwai** [comment]
Получается надо мерджить релиз в девелоп и потом удалять релиз? Как мне исправить это?

**Comment by semwai** [comment]
изменил название пулл реквеста - release to develop

**Comment by SemenMartynov** [comment]
Переименование ПРа не влияент на граф, родители у узла с коммитом остались прежние. Нужно удалить последний коммит в `develop` и сделать его из `release/` ветки
![Screenshot from 2022-12-14 11-57-06](https://user-images.githubusercontent.com/1230054/207551522-6edda4cd-efeb-472b-8d82-ff5873345578.png)

**Comment by semwai** [comment]
Исправил, правда сделал ПР не из release, а из hotfix

**Comment by SemenMartynov** [comment]
`+
