### ISSUE TITLE
Music reognition telegram bot

### ISSUE THREAD

**Issue by donebd** [SemenMartynov/Software-Engineering-2022#163]
Student, group: 3530901/90201
URL: https://github.com/donebd/TgMusicRecognitionBot
Git approach: git-flow

**Comment by SemenMartynov** [comment]
В пайплайне нет возможности запуска руками

**Comment by donebd** [comment]
Да, забыл, добавил. @SemenMartynov fixed

**Comment by SemenMartynov** [comment]
`+
