### ISSUE TITLE
DegreesConverter

### ISSUE THREAD

**Issue by SergeevnaEkaterina** [SemenMartynov/Software-Engineering-2022#165]
Student, group: Gerasina Ekaterina 3530901/90201
URL: https://github.com/SergeevnaEkaterina/DegreesConverter
Git approach: git-flow

**Comment by SemenMartynov** [comment]
`develop` -- это долгоживущая ветка, она не может никуда мерджиться
https://github.com/SergeevnaEkaterina/DegreesConverter/commit/dc6cf595c5e0789aed103142a350d3be030a2c80
