### ISSUE TITLE
Add tests and CI to NoSQL database

### ISSUE THREAD

**Issue by VladislavFetisov** [SemenMartynov/Software-Engineering-2022#178]
Student, group: Fetisov Vladislav 3530901/90202
URL: https://github.com/VladislavFetisov/NoSQL_DB
Git approach: git-flow

**Comment by SemenMartynov** [comment]
А почему коммиты аж от трёх разных пользователей??..
![image](https://user-images.githubusercontent.com/1230054/207788234-09ec4acc-7957-4cec-9412-4a3efcb9a8d9.png)
