### ISSUE TITLE
Telegram bot для парсинга поисковой выдачи YouTube

### ISSUE THREAD

**Issue by kardinalanna** [SemenMartynov/Software-Engineering-2022#188]
Student, group: Карандина Анна, 90202
URL: https://github.com/kardinalanna/Software-Engineering
Git approach:git-flow

**Comment by SemenMartynov** [comment]
А почему `develop` оказался форкнут от `master`?
И почему выполнение `feature/` требований было сделано в `release` ветке?

**Comment by kardinalanna** [comment]
У меня и до этого были проблемы с коммитами, поэтом решила создать новый репозиторий и сделать там красиво)
Ссылка: https://github.com/kardinalanna/Soft_Eng

Ситуация в данном репозитории тоже постараюсь поправить

**Comment by kardinalanna** [comment]
Поняла, попробую поколдовать еще немного

**Comment by SemenMartynov** [comment]
Угу.
Это, по сути, простая штука, но нужно "набить руку".
