### ISSUE TITLE
Converter-USD-to-EUR

### ISSUE THREAD

**Issue by Ralex2105** [SemenMartynov/Software-Engineering-2022#195]
Student, group: Rudnev Alexandr, 3530901/90203
URL: https://github.com/Ralex2105/Converter-USD-to-EUR
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Изменения из `release/1.1` вернуть в `develop`.
Почему коммиты от 2х пользователей?
![image](https://user-images.githubusercontent.com/1230054/208288723-9ca19077-8e22-41b3-aeb9-33f0ecc58720.png)

**Comment by Ralex2105** [comment]
Вернул изменения из release/1.1 в develop.
Коммиты со второго пользователя из второй работы, сейчас гитконфиг настроен правильно и коммиты идут от нужного пользователя

**Comment by SemenMartynov** [comment]
`+
