### ISSUE TITLE
MoeyConverter-KZTtoUSD

### ISSUE THREAD

**Issue by kaamapulyaaa** [SemenMartynov/Software-Engineering-2022#199]
Student, group: 3530901/90101 Курбанова К.Б.
URL:  https://github.com/kaamapulyaaa/MoneyConverter-KZTtoUSD.git
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Пожалуйста прочитай внимательно требования по первой работе.
Итогом работы долежен быть подготовленный репозиторий и декомпозиция задачи на функциональные требования.
Тут не требуется никакого кода и более одного коммита.

**Comment by SemenMartynov** [comment]
Есть какой-то прогресс?
Можно что-то смотреть?

**Comment by kaamapulyaaa** [comment]
> Есть какой-то прогресс? Можно что-то смотреть?

да, загрузила новую ссылку

**Comment by SemenMartynov** [comment]
Окей.
Теперь нужна имплементация в соответсвии с требованиями по второй работе.
Коммиты должны линковаться с issues.
