### ISSUE TITLE
Docs-storage

### ISSUE THREAD

**Issue by OGSegu** [SemenMartynov/Software-Engineering-2022#201]
Student, group: Кривицкий В.В. 90202
URL: https://github.com/OGSegu/Docs-storage
Git approach: git-flow

**Comment by SemenMartynov** [comment]
1. Мы договаривались, что мерджим `--no-ff`.
2. Бейдж для `main` ветки -- он отслеживает именно `main` или показывает результаты любого последнего теста? Кажется, это место для хотфикса.

**Comment by OGSegu** [comment]
Готово. Случайно первым же хотфиксом не то сделал. Пришлось еще один делать

**Comment by SemenMartynov** [comment]
Окей.
Но если "не то", то можно было бы откатить коммит.
