### ISSUE TITLE
Convert money

### ISSUE THREAD

**Issue by RemnevaElena** [SemenMartynov/Software-Engineering-2022#203]
Student, group: Ремнева Елена Евгеньевна, 3530901/90101
URL: https://github.com/RemnevaElena/Software-Engineering.git
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Коммиты от 2х разных пользователей -- пофиксить к 3й работе. И мы договаривались, что коммитим с `--no-ff`, иначе тяжело назад по истории двигаться.
![image](https://user-images.githubusercontent.com/1230054/208502451-01438f7f-3576-4c80-87bd-164539b1b984.png)
