### ISSUE TITLE
Date-Converter

### ISSUE THREAD

**Issue by ivannmm** [SemenMartynov/Software-Engineering-2022#208]
Student, group: Морозов Иван, 3530901/90202
URL: https://github.com/ivannmm/Date-Converter-2
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Тут нарушение `git-flow`: все `feature/` ветки должны форкаться и мерджиться в `develop`.
Что тут по факту произошло?
Каждая новая `feature/` ветка форкалась от прежней `feature/` ветки, и потом заливалась в `develop`. Как мы говорили, в командной разработке такое не работает.
А потом, по той же схеме была форкнута `release/` ветка. В итоге, `develop` в разработке так и не поучаствовала.
![image](https://user-images.githubusercontent.com/1230054/208780802-bf0f7758-204c-41d3-83eb-f74ff7b3eca3.png)

**Comment by SemenMartynov** [comment]
Как успехи? Удалось исправить граф коммитов?

**Comment by ivannmm** [comment]
Да, вроде удалось

**Comment by SemenMartynov** [comment]
`+
