### ISSUE TITLE
Weather Application

### ISSUE THREAD

**Issue by kuznetsona** [SemenMartynov/Software-Engineering-2022#211]
Student, group: Kuznetsova Daria
URL: https://github.com/kuznetsona/Weather/tree/main
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Ветки без префиксов, да ещё использовался fast-forward -- в итоге, я не могу понять что здесь является `feature/` веткой, а что `release`, а ещё откуда и куда что было замерджено.
`dev` остановился на коммите 2aaa4d1936af49feca8d6ccf2db7d20ab162d6ac. Дальше что-то страшное... Кажется я вижу, как долгожевущая ветка была замерджена в короткоживущую.
![image](https://user-images.githubusercontent.com/1230054/208781492-74fdd1e5-c951-4db2-8cc1-1b663f36a6af.png)

**Comment by kuznetsona** [comment]
Исправила)

**Comment by SemenMartynov** [comment]
Да, на много лучше!
К 3-й работе:
1. Не использовать fast forward
2. Убрать `.idea` за `.gitignore`
