### ISSUE TITLE
Weather-forecast

### ISSUE THREAD

**Issue by Lissyona** [SemenMartynov/Software-Engineering-2022#220]
Student, group:  Зигангирова Елизавета 3530901/90101
URL: https://github.com/Lissyona/Wheather_forecast
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Я сейчас вижу 2 коммита.
Получилось так, что изменния в `README.md` привели к прямому коммиту в `master`, а каждый коммит в `master` это новый релиз продукта.
Нужно засквалить эти два коммита, и потом сделать пуш с форсом.

**Comment by Lissyona** [comment]
Исправлено!
