### ISSUE TITLE
Money Converter

### ISSUE THREAD

**Issue by RemnevaElena** [SemenMartynov/Software-Engineering-2022#223]
Student, group: Ремнева Елена Евгеньевна, 101
URL: https://github.com/RemnevaElena/Software-Engineering.git
Git approach: git-flow

**Comment by SemenMartynov** [comment]
1. Не учтены замечания ко второй работе, про коммиты от 2х пользователей.
2. Про FastForward я тоже говорил в замечаниях ко второй работе, так что `33aec43095f8d8eaea75f0a681d8290b4fbf89f4` я воспринимаю как прямой коммит в `master`. Та же история с `0bd46ac484c102b52c8bef88e8ae924d7d3729fa` и с `d71047d5674c92356e08e44f5570a8ae08ed58b3`.
3. В `develop`, тоже прилетело несколько прямых коммитов -- это всё должно было быть закрыто в политиках ещё в первой работе
4. `ec721afb90e70d5683f7fe24c516ac4f1245a82f` зачем мерджить долгоживущую ветку в короткоживущую, почему не наоборот?
5. `d1ae0bd2aded8376f5afe14ba1e447639c1479d2` мердж одной долгоживущей ветки в другую -- Охх...

Нужно повторить правила, какие ветки долгоживущие, какие короткоживущие, кто от кого форкается и кто куда мерджится.

![image](https://user-images.githubusercontent.com/1230054/209461899-e8431445-c127-4016-b5c8-623d6636d4a0.png)

**Comment by RemnevaElena** [comment]
Исправила

**Comment by SemenMartynov** [comment]
1. Всё ещё коммиты от 2х пользователей.
2. Снова марджи с fast forward
3. Ветка `develop` была замерджена в `master`, и потом снова форкнута от `master`
4. Не соблюдена конвенция об именовании веток
5. Последний коммит в `develop` -- это коммит из ветки `master`. Нельзя мерджить долгоживущие ветки друг в друга!
![image](https://user-images.githubusercontent.com/1230054/209507717-e774639a-142e-40c0-b8c1-54d0c792474c.png)
![image](https://user-images.githubusercontent.com/1230054/209507729-b4c0a2d0-6f99-4f70-9d9c-0682349140cf.png)

**Comment by RemnevaElena** [comment]
Здравствуйте, я переделала все заново
URL: https://github.com/RemnevaElena/Money.git

**Comment by SemenMartynov** [comment]
`+
