### ISSUE TITLE
temperatureConverter_ci

### ISSUE THREAD

**Issue by SemenV** [SemenMartynov/Software-Engineering-2022#225]
Student, group: Виноградов Семён 3530901/90101
URL: https://github.com/SemenV/temperatureConverter_ci
Git approach: git-flow
Как Вы посоветовали работал в копии репозитория с 3тей лабораторной, я её сделал. Единственное что нельзя напрямую форкать, только импортировать копию. URL поэтому другой в отличии от 1ой и 2ой лабораторной. (2рая тоже на проверке, замечания исправил)

**Comment by SemenMartynov** [comment]
Окей, но мне этот репозиторий с тестами присылать было не обязательно...
После проверки второй работы -- можно в тот же репозиторий залить третью.
Иначе это был бы обход формальных требований по проверке требований.
