### ISSUE TITLE
Money_converter

### ISSUE THREAD

**Issue by Danil891** [SemenMartynov/Software-Engineering-2022#229]
Student, group:  Cherepkov Danil 3530901/90101
URL: https://github.com/Danil891/Money_Converter/tree/main
Git approach: git-flow

**Comment by Danil891** [comment]
Добрый день, можете посмотреть пожалуйста работу, узнал, что есть возможность получить автомат по дисциплине, но он дается только при условии закрытии всех лаб, экзамен во вторник (27го), сегодня оперативно сделаю 3ю работу, чтобы был ещё день, когда можно что-то исправить

**Comment by SemenMartynov** [comment]
В `README.md` поехала вёрстка.
