### ISSUE TITLE
 Imperial-to-Metric-units converter

### ISSUE THREAD

**Issue by 87yh97** [SemenMartynov/Software-Engineering-2022#232]
Student, group: 
Якубец Никита, 3530901/90101
Сергиенко Никита, 3530901/90101
URL: https://github.com/87yh97/Imperial-to-Metric-units
Git approach: git-flow

**Comment by SemenMartynov** [comment]
У вас было 4 мерджа в `master`, а в списке релизов -- только один, и с версией 2.0...
