### ISSUE TITLE
Imperial-to-Metric-units

### ISSUE THREAD

**Issue by 87yh97** [SemenMartynov/Software-Engineering-2022#235]
Student, group: 
Якубец Никита, гр. 3530901/90101
Сергиенко Никита, гр. 3530901/90101

URL: https://github.com/87yh97/Imperial-to-Metric-units
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Нет возможности запускать тесты вручную

**Comment by 87yh97** [comment]
@SemenMartynov Возможность есть, добавил ее описание в README, проверьте пожалуйста

**Comment by SemenMartynov** [comment]
1. Изменения из `hotfix/` должны возвращаться в `develop`
2. Нет, возможности запуска CI-пайплайна руками нет, это часть требований по 3й работе.

**Comment by 87yh97** [comment]
@SemenMartynov Понял, снова исправил через хотфикс. Посмотрите пожалуйста

**Comment by SemenMartynov** [comment]
`+
