### ISSUE TITLE
Alcohol Converter

### ISSUE THREAD

**Issue by Segezha** [SemenMartynov/Software-Engineering-2022#238]
Student, group: Petrov Maxim 3530901/90101
URL: https://github.com/Segezha/AlcoholConverter
Git approach: git-flow

**Comment by SemenMartynov** [comment]
1. Коммиты не слинкованы с issues
2. `feature/` ветки форкаются от `develop`, а не от последнего коммита в другой `feature/` ветке
3. Нарушено соглашение о префиксах для `fteature/` ветках
