### ISSUE TITLE
Date-Converter

### ISSUE THREAD

**Issue by ivannmm** [SemenMartynov/Software-Engineering-2022#246]
Student, group: Морозов Иван, 3530901/90202
URL: https://github.com/ivannmm/date-convert
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Всё де добавление бейджей -- это скорее фича, и логично было бы класть в коммит с фичей, а не в релизной ветке. Ещё изменения из релизной ветки должны возвращаться в девелоп.
