### ISSUE TITLE
Task-tracker

### ISSUE THREAD

**Issue by Valaubr** [SemenMartynov/Software-Engineering-2022#252]
Student, group: Чупрынин И.А. 3530901/90101
URL: https://github.com/Valaubr/Task-Tracker
Git approach: TBD

**Comment by SemenMartynov** [comment]
А где бейджик с результатами тестов?

**Comment by Valaubr** [comment]
Разве не внизу ридми должен быть?

**Comment by SemenMartynov** [comment]
Обычно в самом верху, но этого в требованиях нет.
Нужно хоть где-нибудь в репозитории.

**Comment by Valaubr** [comment]
Всё, поправил, не поставил указатель на main и он почему то ствил false всегда.

**Comment by SemenMartynov** [comment]
Окей!)
