### ISSUE TITLE
YouTubeGifAndSoundBot

### ISSUE THREAD

**Issue by Julia-Chekulaeva** [SemenMartynov/Software-Engineering-2022#255]
Student, group: Chekulaeva, 3530901/90203
URL: https://github.com/Julia-Chekulaeva/YouTubeGifAndSoundBot
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Изменения не были доставлены в ветку `main`.
Нет бэджиков с итогами тестирования.

**Comment by SemenMartynov** [comment]
@Julia-Chekulaeva ping
