### ISSUE TITLE
Chess Moves Finder

### ISSUE THREAD

**Issue by ilyaorlov25** [SemenMartynov/Software-Engineering-2022#258]
Student, group: Илья Орлов, 3530901/90203
URL: https://github.com/ilyaorlov25/ChessMovesFinder
Git approach: git-flow

**Comment by ilyaorlov25** [comment]
I have already sent the first task, but there are some troubles with API I wanted to use, so I chose a new task.

**Comment by SemenMartynov** [comment]
`+
