### ISSUE TITLE
BabyBlockchain

### ISSUE THREAD

**Issue by kechinvv** [SemenMartynov/Software-Engineering-2022#263]
Student, group: Кечин Валерий, 3530901/90202
URL: https://github.com/kechinvv/BabyBlockchain
Any comments: TBD workflow, ktor

**Comment by kechinvv** [comment]
У меня украли название (╯︵╰,)

**Comment by SemenMartynov** [comment]
Кажется, это название было на поверхности...

**Comment by kechinvv** [comment]
Тут есть небольшая предыстория)) воришка даже не отпирался…

**Comment by SemenMartynov** [comment]
`+
