### ISSUE TITLE
Blockchan

### ISSUE THREAD

**Issue by Slava0135** [SemenMartynov/Software-Engineering-2022#265]
Student, group: Ковалевский Вячеслав Максимович 3530901/90201
URL: https://github.com/Slava0135/blockchan
Any comments: TBD, golang

**Comment by SemenMartynov** [comment]
В компоузе можно было добавить `depends_on` для 1й и 2й ноды, и не передавать им флаги. Они бы так могла понять, что можно искать соседей.
