### ISSUE TITLE
Блокчейн на минималках

### ISSUE THREAD

**Issue by jykaswift** [SemenMartynov/Software-Engineering-2022#266]
Student, group:  Borisov Eugene | 3530901/90201
URL:  https://github.com/jykaswift/networklabs
Any comments: python, flask

**Comment by SemenMartynov** [comment]
Нужно проверить пути.
```
smart@thinkpad$ docker-compose up
[+] Running 3/3
 ✔ Container node2  Created                                                                                                                                                                                                              0.1s 
 ✔ Container node1  Created                                                                                                                                                                                                              0.1s 
 ✔ Container node0  Created                                                                                                                                                                                                              0.0s 
Attaching to node0, node1, node2
node2  | Traceback (most recent call last):
node2  |   File "/app/src/start.py", line 3, in <module>
node2  |     from node import Node
node2  |   File "/app/src/node.py", line 1, in <module>
node2  |     from src.block import Block
node2  | ModuleNotFoundError: No module named 'src'
node1  | Traceback (most recent call last):
node1  |   File "/app/src/start.py", line 3, in <module>
node1  |     from node import Node
node1  |   File "/app/src/node.py", line 1, in <module>
node1  |     from src.block import Block
node1  | ModuleNotFoundError: No module named 'src'
node0  | Traceback (most recent call last):
node0  |   File "/app/src/start.py", line 3, in <module>
node0  |     from node import Node
node0  |   File "/app/src/node.py", line 1, in <module>
node0  |     from src.block import Block
node0  | ModuleNotFoundError: No module named 'src'
node1 exited with code 1
node2 exited with code 1
node0 exited with code 1
```

**Comment by jykaswift** [comment]
Исправил, питончик с импортами потролил 

> Нужно проверить пути.
> 
> ```
> smart@thinkpad$ docker-compose up
> [+] Running 3/3
>  ✔ Container node2  Created                                                                                                                                                                                                              0.1s 
>  ✔ Container node1  Created                                                                                                                                                                                                              0.1s 
>  ✔ Container node0  Created                                                                                                                                                                                                              0.0s 
> Attaching to node0, node1, node2
> node2  | Traceback (most recent call last):
> node2  |   File "/app/src/start.py", line 3, in <module>
> node2  |     from node import Node
> node2  |   File "/app/src/node.py", line 1, in <module>
> node2  |     from src.block import Block
> node2  | ModuleNotFoundError: No module named 'src'
> node1  | Traceback (most recent call last):
> node1  |   File "/app/src/start.py", line 3, in <module>
> node1  |     from node import Node
> node1  |   File "/app/src/node.py", line 1, in <module>
> node1  |     from src.block import Block
> node1  | ModuleNotFoundError: No module named 'src'
> node0  | Traceback (most recent call last):
> node0  |   File "/app/src/start.py", line 3, in <module>
> node0  |     from node import Node
> node0  |   File "/app/src/node.py", line 1, in <module>
> node0  |     from src.block import Block
> node0  | ModuleNotFoundError: No module named 'src'
> node1 exited with code 1
> node2 exited with code 1
> node0 exited with code 1
> ```

**Comment by SemenMartynov** [comment]
`+`
