### ISSUE TITLE
PythonBlockchain

### ISSUE THREAD

**Issue by sergeyfedorov02** [SemenMartynov/Software-Engineering-2022#268]
Student, group: Fedorov Sergey, 3530901/90201
URL: https://github.com/sergeyfedorov02/PythonBlockchain.git
Any comments: Python + Flask, git-flow

**Comment by SemenMartynov** [comment]
Кажется, что инструкция по автозапуску `docker` через `systemd` избыточна -- это out-of-the-scope, и не все используют именно `systemd`)
