### ISSUE TITLE
SmallBlockchain

### ISSUE THREAD

**Issue by ebukreev** [SemenMartynov/Software-Engineering-2022#269]
Student, group: Букреев Евгений Александрович, 3530901/90203
URL: https://github.com/ebukreev/SmallBlockchain
Any comments: TBD, Kotlin Ktor pure TCP sockets

**Comment by SemenMartynov** [comment]
Кажется, что инструкция по автозапуску `docker` через `systemd` избыточна -- это out-of-the-scope, и не все используют именно `systemd`)
