### ISSUE TITLE
BlockChain without strain

### ISSUE THREAD

**Issue by Morphylix** [SemenMartynov/Software-Engineering-2022#275]
Student, group: Borovik Dmitry, 3530901/90203
URL: https://github.com/Morphylix/blockchain-without-strain/tree/dev
Any comments: git-flow, Kotlin, Ktor

**Comment by SemenMartynov** [comment]
Портмаппинг не работает, когда сеть в режиме хоста... Тут режим хоста не нужен, ноды вполне могут обращаться друг к другу по заранее известным именам хостов. Для универсальности, можно эти имена прокидывать через переменные окружения.

Ещё, в инструкции мы собираем ноды с одним именем `docker build -t blockchain-without-strain .` а запускать пытаемся с другим `image: borovikdv/blockchain`

Ну и не стоит стектрейсы прокидывать в лог пользователю, стоит все исключительные ситуации обрабатывать внутри.
