### ISSUE TITLE
Alexander Block

### ISSUE THREAD

**Issue by igalaxy00** [SemenMartynov/Software-Engineering-2022#278]
Student, group: Галактионов Игорь 353090190203
URL: https://github.com/igalaxy00/A.Block
Any comments: Python gitflow

**Comment by igalaxy00** [comment]
Ночь, улица, фонарь, аптека…

**Comment by igalaxy00** [comment]
Ночь, улица, фонарь, аптека....

**Comment by SemenMartynov** [comment]
`cd PythonBlockchain` вот, кстати, и не обязательно, что после `git clone` будет папка именно с таким именем...
