### ISSUE TITLE
Network Programming lab

### ISSUE THREAD

**Issue by PolinaRubinova** [SemenMartynov/Software-Engineering-2022#286]
Student, group: Rubinova Polina 3530901/90201
URL: https://github.com/PolinaRubinova/Network_Programming_lab
Any comments: git-flow, Kotlin, Ktor

**Comment by SemenMartynov** [comment]
Классический набор замечаний:
1. В `readme` рекомендуется собирать образ как `docker build -t Network_Programming_lab .`, но docker не позволит иметь такое имя для контейнера
2. В `docker-compose` используется одновременно и `network_mode: host` и `port mapping`
3. Ноды идентифицируются номерами портов, а не именами хостов
4. Параметры запуска должны оборачиваться переменными окружения
5. Эксепшены в логе пользователя.
Я бы сказал, что не доработано, но времени осталось совсем мало, и главное (сетевое взаимодействие) есть.
