### ISSUE TITLE
BlockChain task

### ISSUE THREAD

**Issue by SergeevnaEkaterina** [SemenMartynov/Software-Engineering-2022#287]
Student, group: Gerasina Ekaterina 3530901/90201
URL: https://github.com/SergeevnaEkaterina/BlockChain
Any comments: git-flow, Java

**Comment by SemenMartynov** [comment]
`~/.m2:/root/.m2` -- я уже у кого-то видел проброс `.m2` в контейнер. А для чего это?

**Comment by SergeevnaEkaterina** [comment]
@SemenMartynov 
Я шарю между контейнерами папку с мавеном, чтобы каждый раз внутри контейнера все зависимости не качать, а просто брать уже скачанные. Но без этого тоже будет работать. https://github.com/carlossg/docker-maven/blob/main/README.md#reusing-the-maven-local-repository

**Comment by SemenMartynov** [comment]
А зачем нам maven-овские либы, если у нас уже есть контейнер с готовым jar-ником?

**Comment by SergeevnaEkaterina** [comment]
@SemenMartynov 
Исправила, мавеновские либы убрала

**Comment by SemenMartynov** [comment]
```
smart@thinkpad$ docker compose --verbose up
[+] Running 3/3
 ✔ Container node1  Created                                                                                                       0.1s 
 ✔ Container node2  Created                                                                                                       0.1s 
 ✔ Container node3  Created                                                                                                       0.1s 
Attaching to node1, node2, node3
node2  | ОШИБКА: Файл свойств отсуствует!
node2  | ОШИБКА: Файл свойств отсуствует!
node2  | ОШИБКА: Файл свойств отсуствует!
node2  | ОШИБКА: Файл свойств отсуствует!
node2  | ОШИБКА: Файл свойств отсуствует!
node2  | Exception in thread "main" java.lang.NullPointerException: null algorithm name
node2  |        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
node2  |        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:175)
node2  |        at logics.BlockChain.calculateHashSum(BlockChain.java:40)
node2  |        at model.Block.<init>(Block.java:18)
node2  |        at logics.BlockChain.<init>(BlockChain.java:17)
node2  |        at logics.BlockchainNode.<init>(BlockchainNode.java:21)
node2  |        at logics.BlockchainNode.main(BlockchainNode.java:31)
node3  | ОШИБКА: Файл свойств отсуствует!
node3  | ОШИБКА: Файл свойств отсуствует!
node3  | ОШИБКА: Файл свойств отсуствует!
node3  | ОШИБКА: Файл свойств отсуствует!
node3  | ОШИБКА: Файл свойств отсуствует!
node3  | Exception in thread "main" java.lang.NullPointerException: null algorithm name
node3  |        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
node3  |        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:175)
node3  |        at logics.BlockChain.calculateHashSum(BlockChain.java:40)
node3  |        at model.Block.<init>(Block.java:18)
node3  |        at logics.BlockChain.<init>(BlockChain.java:17)
node3  |        at logics.BlockchainNode.<init>(BlockchainNode.java:21)
node3  |        at logics.BlockchainNode.main(BlockchainNode.java:31)
node1  | ОШИБКА: Файл свойств отсуствует!
node1  | ОШИБКА: Файл свойств отсуствует!
node1  | ОШИБКА: Файл свойств отсуствует!
node1  | ОШИБКА: Файл свойств отсуствует!
node1  | ОШИБКА: Файл свойств отсуствует!
node1  | Exception in thread "main" java.lang.NullPointerException: null algorithm name
node1  |        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
node1  |        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:175)
node1  |        at logics.BlockChain.calculateHashSum(BlockChain.java:40)
node1  |        at model.Block.<init>(Block.java:18)
node1  |        at logics.BlockChain.<init>(BlockChain.java:17)
node1  |        at logics.BlockchainNode.<init>(BlockchainNode.java:21)
node1  |        at logics.BlockchainNode.main(BlockchainNode.java:31)
node2 exited with code 1
node3 exited with code 1
node1 exited with code 1
```

**Comment by SergeevnaEkaterina** [comment]
@SemenMartynov не считывался .properties файл, добавила проброс файла настроек проекта.
PS C:\Users\geras\IdeaProjects\BlockChainGit> docker-compose up
[+] Running 0/3
 - node3 Warning                                                                                                                                                        1.8s 
 - node1 Warning                                                                                                                                                        1.7s 
 - node2 Warning                                                                                                                                                        1.8s 
[+] Building 63.7s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 32B                                                                                                                                     0.0s 
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/openjdk:11                                                                                                           0.0s 
 => [internal] load metadata for docker.io/library/maven:3.6.1-jdk-11                                                                                                   0.0s
 => [build 1/4] FROM docker.io/library/maven:3.6.1-jdk-11                                                                                                               0.0s 
 => CACHED [stage-1 1/3] FROM docker.io/library/openjdk:11                                                                                                              0.0s 
 => [internal] load build context                                                                                                                                       0.1s 
 => => transferring context: 21.02kB                                                                                                                                    0.1s 
 => CACHED [build 2/4] WORKDIR /app                                                                                                                                     0.0s
 => [build 3/4] COPY . .                                                                                                                                                0.1s 
 => [build 4/4] RUN mvn verify package                                                                                                                                 63.0s
 => [stage-1 2/3] COPY --from=build /app/target/BlockChainRealization-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/local/lib/BlockChainRealization.jar                   0.1s
 => [stage-1 3/3] COPY src/main/resources/blockchain.properties src/main/resources/blockchain.properties                                                                0.1s
 => exporting to image                                                                                                                                                  0.1s
 => => exporting layers                                                                                                                                                 0.1s
 => => writing image sha256:bb3dd76f7368bd0b34813bb5bc6b1874d759e68d068d15b1ce25368811db0daf                                                                            0.0s
 => => naming to docker.io/library/blockchain                                                                                                                           0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 3/3
 - Container node3  Created                                                                                                                                             0.2s 
 - Container node1  Created                                                                                                                                             0.2s 
 - Container node2  Created                                                                                                                                             0.2s 
Attaching to node1, node2, node3
node1  | Node 0 found: e3311d2b642df8bb6737bf532eb10c90acd8f875715650b82b6f6fd0b8050000
node1  | Node 0 data: genesis
node1  | Node 0 nonce: -831205351
node1  | Node 1 found: bf540edd1f29f74408da36a143bac73c53f0e47f9728226dc1971d6ab9dc0000
node1  | Node 1 data: node1
node1  | Node 1 nonce: -935473379
node1  | Node 2 found: 9ae3bc94ce1ade7f090f58e0f920347e668354f0dad27f965c9708fc38090000
node1  | Node 2 data: node2
node1  | Node 2 nonce: -947206067
node2  | Node 0 found: 06a55bf7a6a81d6739e2802741ad22d23468ed1dbf06813b23f178dbf0f00000
node2  | Node 0 data: genesis
node2  | Node 0 nonce: -454502309
node1  | Node 3 found: 11c69cdf66b21d8e82fc0e050d9a9d42d81e1c4dc053459722e99022a2e50000
node1  | Node 3 data: node3
node1  | Node 3 nonce: 1393993130
node3  | Node 0 found: 76a05179455f4985030cf8a2f0afaf38942017969b0918ce061aa8bfc9a30000
node3  | Node 0 data: genesis
node3  | Node 0 nonce: -74323759
node3  | Node 1 found: eea501de496e51b29539062be59860cbff3b6c7508334dc887f6743699f70000
node3  | Node 1 data: node1

**Comment by SemenMartynov** [comment]
`+`
