### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by Ralex2105** [SemenMartynov/Software-Engineering-2022#293]
Student, group: Руднев Александр, 3530901/90203
URL: https://github.com/Ralex2105/Blockchain
Any comments: python, git-flow

**Comment by SemenMartynov** [comment]
В ридми мы собираем `ralex2105/blockchain/src/main:latest` а в компоузе запускаем `ralex/blockchain`.

Можно добавить в вывод информацию по блокам? Кто что сгенерил, кому отправил? Просто я вижу только "200 ОК"...

**Comment by Ralex2105** [comment]
Исправил

**Comment by SemenMartynov** [comment]
Окей. Но там есть бага с индексом))
