### ISSUE TITLE
BlockChain

### ISSUE THREAD

**Issue by nenailya** [SemenMartynov/Software-Engineering-2022#296]
Student, group: Загрутдинова Наиля, 3530901/90201
URL: https://github.com/nenailya/BlockChain
Any comments: Java, git-flow

**Comment by SemenMartynov** [comment]
`      - ~/.m2:/root/.m2` -- для чего? Мы же специально делаем multistage build...

**Comment by nenailya** [comment]
@SemenMartynov, для повторного использования мавена.... Как-то сразу упустила что при multistage build можно и без этого обойтись

**Comment by SemenMartynov** [comment]
А где ты повторно используешь мавен?
И для чего `- .:/app`?..

**Comment by nenailya** [comment]
Исправила. Убрала лишние пробросы директорий, т.к. в готовом контейнере содержится проект без зависимостей.

**Comment by SemenMartynov** [comment]
`+`
