### ISSUE TITLE
block_chain

### ISSUE THREAD

**Issue by yantimirov-timur** [SemenMartynov/Software-Engineering-2022#305]
Student, group: Yantimirov Timur, 3530901/90203
URL: https://github.com/yantimirov-timur/block_chain
Any comments: pure java sockets on kotlin

**Comment by SemenMartynov** [comment]
У нас есть docker, не нужно хардкодить порты...

**Comment by SemenMartynov** [comment]
А куда пропало репо?..

**Comment by yantimirov-timur** [comment]
@SemenMartynov Недавно чистил гитхаб и решил удалить, так как issue закрыто. Вернул репу обратно.

**Comment by SemenMartynov** [comment]
Нужно какое-то время подержать репо на месте, чтобы ВМ посмотрел тесты.
Потом можно, к примеру, репо сделать приватным...
