### ISSUE TITLE
SimpleBlockChain

### ISSUE THREAD

**Issue by DenZhid** [SemenMartynov/Software-Engineering-2022#306]
Student, group: Zhidkov Denis, 3530901/90202
URL: https://github.com/DenZhid/SimpleBlockChain
Any comments: Git-flow, java-sockets, java

**Comment by SemenMartynov** [comment]
```
smart@thinkpad$ docker compose up
[+] Running 3/3
 ✔ Container secondNode  Created                                           0.1s 
 ✔ Container firstNode   Created                                           0.1s 
 ✔ Container thirdNode   Created                                           0.0s 
Attaching to firstNode, secondNode, thirdNode
firstNode   | Error: Unable to access jarfile /simpleblockchain/build/libs/SimpleBlockChain-1.0.jar
secondNode  | Error: Unable to access jarfile /simpleblockchain/build/libs/SimpleBlockChain-1.0.jar
thirdNode   | Error: Unable to access jarfile /simpleblockchain/build/libs/SimpleBlockChain-1.0.jar
firstNode exited with code 1
secondNode exited with code 1
thirdNode exited with code 1
```

Там ещё тесты в `main` завалились.
Ещё нам тут не нужен `network_mode: host`, в `NODES_IN_CLUSTER_ADDRESSES` можно передавать имена хостов, и всё время использовать дефолтный порт.

**Comment by DenZhid** [comment]
Исправил.
Попробовал убрать `network_mode: host`, но без него не работает :(

**Comment by SemenMartynov** [comment]
> но без него не работает

Ну да, нужно же ещё логику доработать))
Сейчас контейнеры шарят между собой один сетевой интерфейс -- интерфейс хоста.
А то что я предлагаю, это работа в изолированном сетевом сегменте, где можно будет обращаться по имени хоста.
