### ISSUE TITLE
Polychain

### ISSUE THREAD

**Issue by iTteruya** [SemenMartynov/Software-Engineering-2022#308]
Student, group: Ivanov Timur, 3530901/90201
URL: https://github.com/iTteruya/polychain
Any comments: git-flow, Python + Flask

**Comment by SemenMartynov** [comment]
`network_mode: host` -- используй ИПы контейнеров для коннекта

**Comment by iTteruya** [comment]
Сделал

**Comment by SemenMartynov** [comment]
Окей.
Только пиры лучше не хардкодить, а получать через переменные окружения. Это избавит от проблем при масштабировании.
