### ISSUE TITLE
JavaBlockchainForEXP

### ISSUE THREAD

**Issue by Houston613** [SemenMartynov/Software-Engineering-2022#309]
Student, group: Chervak A.V. 3530901/90202
URL:  https://github.com/Houston613/JavaBlockchainForEXP
Any comments: java sockets, gitflow

**Comment by SemenMartynov** [comment]
`network_mode: host` -- используй доменные имена контейнеров для коннекта

**Comment by Houston613** [comment]
убрал `network_mode: host`

**Comment by SemenMartynov** [comment]
`+`
