### ISSUE TITLE
Flockbrain Blockchain

### ISSUE THREAD

**Issue by tengen-toppa-gurren-lagann** [SemenMartynov/Software-Engineering-2022#311]
Student, group: Ундольский Алексей, 3530901/90203
URL:  https://github.com/tengen-toppa-gurren-lagann/flockbrain
Any comments: Реализовано с использованием фреймворка Bottle.

**Comment by SemenMartynov** [comment]
Давай, плиз, от этого избавимся `network_mode: "host"`.
И параметры в приложение лучше передавать через переменные окружения.

**Comment by tengen-toppa-gurren-lagann** [comment]
Сделано

**Comment by SemenMartynov** [comment]
Окей.
А если адресов больше трёх? Я бы принимал строку с запятой в качестве разделителя, и укладывал бы эти адреса в массив.
