### ISSUE TITLE
BlockChain

### ISSUE THREAD

**Issue by VladislavFetisov** [SemenMartynov/Software-Engineering-2022#312]
Student, group: Fetisov Vladislav 3530901/90202
URL: https://github.com/VladislavFetisov/BlockChain/tree/1.0.0
Any comments: Python, Git-flow

**Comment by SemenMartynov** [comment]
Да как так-то?..
![image](https://user-images.githubusercontent.com/1230054/233802769-914733a7-1b90-4a8e-8994-9438cadf62f1.png)
