### ISSUE TITLE
Task Blockchain 

### ISSUE THREAD

**Issue by galievaregina** [SemenMartynov/Software-Engineering-2022#313]
Student, group: Galieva Regina, 3530901/90202
URL: https://github.com/galievaregina/MyFirstBlockChain
Any comments: gitflow, Python, Flask

**Comment by SemenMartynov** [comment]
Вот такой хардкод
```
    if service == 1:
        port1, port2, port3 = 5000, 5001, 5002
    elif service == 2:
        port1, port2, port3 = 5001, 5000, 5002
    else:
        port1, port2, port3 = 5002, 5000, 5001
```
Не позволит дальше масштабироваться по горизонтали.

Посмотри на коммент тут -- https://github.com/SemenMartynov/Software-Engineering-2022/issues/310
