### ISSUE TITLE
MiniButNimbleBlockChain

### ISSUE THREAD

**Issue by kardinalanna** [SemenMartynov/Software-Engineering-2022#314]
Student, group: Karandina Anna, 3530901/90202
URL: https://github.com/kardinalanna/MiniButNimbleBlockChain
Any comments: gitflow, Node.js

**Comment by SemenMartynov** [comment]
`network_mode: host` давай откажемся от привязки к сетевому интерфейсу хоста.

**Comment by kardinalanna** [comment]
fix

**Comment by SemenMartynov** [comment]
в ридми мы собираем `MiniButNimbleBlockChain:latest` а в компоузе запускаем почему-то `kardinalanna/blockchain`...
