### ISSUE TITLE
cepochka blokov

### ISSUE THREAD

**Issue by sevenineone** [SemenMartynov/Software-Engineering-2022#317]
Student, group: Dubynin Alexey, 3530901/90201
URL: https://github.com/sevenineone/cepochka_blokov
Any comments: Python + Flask, git-flow

**Comment by SemenMartynov** [comment]
Давай уберём `network_mode: host`.

**Comment by sevenineone** [comment]
@SemenMartynov, пофикшено!

**Comment by SemenMartynov** [comment]
Хардкод с номерами портов выглядит так себе... Почему бы не передавать это как параметры окружения?..
