### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by Artyom-boop** [SemenMartynov/Software-Engineering-2022#318]
Student, group: Sidorov Artem, 3530901/90203
URL: https://github.com/Artyom-boop/Blockchain
Any comments: Java, git-flow

**Comment by SemenMartynov** [comment]
`network_mode: host` -- давай всё же расположим сетевые сервисы не в рамках одного хоста

**Comment by Artyom-boop** [comment]
Исправил

**Comment by SemenMartynov** [comment]
`+`
