### ISSUE TITLE
Simplest BlockChain

### ISSUE THREAD

**Issue by AntunovichPYU** [SemenMartynov/Software-Engineering-2022#319]
Student, group: Antunovich Pavel, 3530901/90203
URL: https://github.com/AntunovichPYU/BlockChain
Any comments: Python, Flask, gitflow

**Comment by SemenMartynov** [comment]
`network_mode: host` -- давай уберём это.

**Comment by AntunovichPYU** [comment]
Сделано

**Comment by SemenMartynov** [comment]
`+`
