### ISSUE TITLE
Simple Blochain Impl

### ISSUE THREAD

**Issue by VladislavFetisov** [SemenMartynov/Software-Engineering-2022#321]
Student, group: Fetisov Vladislav 3530901/90202
URL: https://github.com/VladislavFetisov/blockChainSimple
Any comments: java, one-nio

**Comment by SemenMartynov** [comment]
Смотри какое у тебя дерево коммитов получается... А теперь представь, что в ветке master, тебе нужно откатить только вторую фичу, и не трогать остальные?.. А до кучи, представь, что всего фичей нам три десятка, и не все из них ты писал.
![image](https://user-images.githubusercontent.com/1230054/235455984-422f3ecb-3b92-40ee-8234-9d4950509246.png)
