### ISSUE TITLE
https://github.com/nikiens/blkchain

### ISSUE THREAD

**Issue by nikiens** [SemenMartynov/Software-Engineering-2022#324]
Student, group: Аникин Дмитрий, 3530901/90202
URL: https://github.com/nikiens/blkchain
Any comments: git-flow, flask, python

**Comment by SemenMartynov** [comment]
`network_mode: host` -- у всех одна и та же проблема)) Не надо использовать сетевой стек хоста.

**Comment by nikiens** [comment]
fixed

**Comment by SemenMartynov** [comment]
Мне только не нравится алгоритм определения соседей... Нода может быть запущена в разных условиях. Так что соседей лучше сразу целиком (полный УРЛ) передавать как переменную окружения.
