### ISSUE TITLE
Send Nodes, a tiny blockchain

### ISSUE THREAD

**Issue by mmoschenskikh** [SemenMartynov/Software-Engineering-2022#327]
Student, group: Maxim Moschenskikh, 3530901/90201
URL: https://github.com/mmoschenskikh/SendNodes
Any comments: TBD, Kotlin. No tests as Software Testing course is successfully completed.

**Comment by SemenMartynov** [comment]
> No tests as Software Testing course is successfully completed.
Но тесты же пишутся не ради одного зачёта... Это просто один из способов создания хорошего, поддерживаемого кода.
