### ISSUE TITLE
BlockchainJava

### ISSUE THREAD

**Issue by ilyaorlov25** [SemenMartynov/Software-Engineering-2022#332]
Student, group: Ilya Orlov, 3530901/90203
URL: https://github.com/ilyaorlov25/BlockchainJava
Any comments: Java, git-flow (new attempt, the previous was #325)

**Comment by SemenMartynov** [comment]
Увы, это работу я уже видел.

**Comment by ilyaorlov25** [comment]
@SemenMartynov да, действительно, вдохновился одним из вариантов реализации одногруппника. Но сейчас тогда исправил старый вариант — #325 — починил, чтобы работало без `network_mode: host`, сможете ли заново посмотреть то issue?

**Comment by SemenMartynov** [comment]
Это не вдохновился. Это плагиат. Нужно называть вещи своими именами.

**Comment by ilyaorlov25** [comment]
Да, извините, переживал из-за двух комиссий за день, думая, что всё надо будет сделать за тот день. После этого всё-таки вернулся к исправлению замечания в изначальной работе (#335).
