### ISSUE TITLE
calendar-app

### ISSUE THREAD

**Issue by Stoncs** [SemenMartynov/Software-Engineering-2022#44]
Student, group: Юрченко А.И., 3530901/90101
URL: https://github.com/Stoncs/TALKium-forum
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Задача кажется довольно сложной... Я думаю только на продумываение логики уйдёт уйма времени.
Может что-то проще сделать? Какой-нибудь TODO лист?

**Comment by Stoncs** [comment]
TODO-лист уже делал.. Календарь с возможностью заметок пойдёт?

**Comment by Stoncs** [comment]
Student, group: Юрченко А.И., 3530901/90101
URL: https://github.com/Stoncs/Calendar-App
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Пойдёт что угодно)) Это я скорее к тому, чтоб не брать слишком сложную задачу для разработки...
Коммиты которые сейчас в репо -- нужно засквашить. Иначе я вижу несколько прямых коммитов в `master` и ещё один мердж из ветки с префиксом `Stoncs/`. Нужно следовать требованиям git-flow.

**Comment by Stoncs** [comment]
fixed

**Comment by SemenMartynov** [comment]
`+
