### ISSUE TITLE
Horoscope telegram bot

### ISSUE THREAD

**Issue by galievaregina** [SemenMartynov/Software-Engineering-2022#45]
Student, group: Галиева Регина 3530901/90202
URL: https://github.com/galievaregina/horoscope_telegram_bot
Git approach: git-flow

**Comment by SemenMartynov** [comment]
1. Не могу получить доступ к Trello, там не публичная борда
2. Если следовать git-flow, не должно быть такого количества прямых коммитов в master... Сейчас нужно их засквошить

**Comment by galievaregina** [comment]
Исправила замечания.Сделала доску в Trello публичной  и засквошила коммиты

**Comment by SemenMartynov** [comment]
Не-а, всё равно анонимно не пускает доску открыть(
И коммитов опять стало 2))

**Comment by galievaregina** [comment]
Вот теперь точно все

**Comment by SemenMartynov** [comment]
`+
