### ISSUE TITLE
Degree , minute seconds converter

### ISSUE THREAD

**Issue by igalaxy00** [SemenMartynov/Software-Engineering-2022#5]
Student, group: Galaktionov Igor 3530901/90203
URL: https://github.com/igalaxy00/Converter
Git approach: git-flow

**Comment by SemenMartynov** [comment]
With the git-flow, you should avoid direct commits to the main branch
https://github.com/igalaxy00/Converter/commit/c1d9b5c2247314af4b286ff2d1b3b00d2607b4c2
