### ISSUE TITLE
Meme Creator Bot for Telegram

### ISSUE THREAD

**Issue by mmoschenskikh** [SemenMartynov/Software-Engineering-2022#54]
Student, group: Maxim Moschenskikh, 3530901/90201
URL: https://github.com/mmoschenskikh/meme-creator-telegram-bot
Git approach: git-flow

**Comment by SemenMartynov** [comment]
`.idea` убрать из репо.
Либо в 1-м коммите и засквашить, либо в фича-ветке (но это хуже, т.к. сборщик мусора не сможет выкинуть эти файлы)
