### ISSUE TITLE
JPG <-> PNG image converter

### ISSUE THREAD

**Issue by WorryWarrior** [SemenMartynov/Software-Engineering-2022#6]
Student, group: Aleksandrov Daniil, 3530901/90203
URL: https://github.com/WorryWarrior/JpgPngConverter
Git approach: gitflow

**Comment by SemenMartynov** [comment]
You need to provide 5 functional requirements

**Comment by WorryWarrior** [comment]
@SemenMartynov Fixed

**Comment by SemenMartynov** [comment]
`+
