### ISSUE TITLE
Celsius-Fahrenheit converter

### ISSUE THREAD

**Issue by k1eden** [SemenMartynov/Software-Engineering-2022#60]
Student, group: Garik Beglaryan, 3530901/90101
URL: https://github.com/k1eden/Celsius-Fahrenheit
Git approach: git flow

**Comment by SemenMartynov** [comment]
`git-flow` предполагает, что каждый коммит в `main` -- это новый релиз.
Нужно сделать squash коммитов.

**Comment by k1eden** [comment]
done!

**Comment by SemenMartynov** [comment]
`+
