### ISSUE TITLE
OBJ-viewer, lab 2

### ISSUE THREAD

**Issue by vasilievan** [SemenMartynov/Software-Engineering-2022#73]
Student, group: Васильев Алексей, 3530901/90203
URL: https://github.com/vasilievan/software_engineering
Git approach: git-flow
Docker image: https://hub.docker.com/r/enthusiasticprogrammer/obj_viewer

**Comment by SemenMartynov** [comment]
Не вижу где git-flow... `master` и `develop` указывают на один коммит. Никаких признков `feature/` и `release/` веток.
И в докере тоже всё в одном образе собирается.

**Comment by vasilievan** [comment]
Fixed:
- feature branch added and used;
- release branch added and used;
- multistage-building in Dockerfile added.

**Comment by SemenMartynov** [comment]
`feature/` -- это короткоживущая ветка, она создаётся под каждую `issue`

**Comment by vasilievan** [comment]
Fixed.

**Comment by SemenMartynov** [comment]
Ok
