### ISSUE TITLE
Imperial to metric units conversion

### ISSUE THREAD

**Issue by ddoubleo** [SemenMartynov/Software-Engineering-2022#77]
Student, group: Sergienko Nikita 3530901/90101 Yakubets Nikita 3530901/90101
URL: https://github.com/87yh97/Imperial-to-Metric-units
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Нельзя делать прямые коммиты в `develop` и `master`.

**Comment by 87yh97** [comment]
Мы и не делали прямых коммитов, кроме initial((((
Создали ветку feature_readme, слили с develop, после чего слили develop с main-ом. Просто после слияния с develop гитхаб предложил удалить feature_readme, что мы и сделали.

**Comment by SemenMartynov** [comment]
Сейчас остался только один прямой коммит в `master` который нужно убрать -- 5f3f4e3b7b3c097973ccba09d1ea3205bfadafc3

**Comment by SemenMartynov** [comment]
@ddoubleo @87yh97 Какие новости?)

**Comment by SemenMartynov** [comment]
@ddoubleo @87yh97 ping

**Comment by 87yh97** [comment]
> @ddoubleo @87yh97 ping

pong

**Comment by SemenMartynov** [comment]
Как прогресс за 3 недели?
Всё ещё вижу 2 коммита...

**Comment by 87yh97** [comment]
> Сейчас остался только один прямой коммит в `master` который нужно убрать -- 5f3f4e3b7b3c097973ccba09d1ea3205bfadafc3

Поправили, сделали заново ветку feature_comprehensive_readme, слили ее с develop, из develop сделали release, потом release слили с main.

**Comment by SemenMartynov** [comment]
В качестве префикса, лучше использоват `feature/`, тогда всякие GUI тулы смогут группировать такие ветки
