### ISSUE TITLE
Degree , minute seconds converter

### ISSUE THREAD

**Issue by igalaxy00** [SemenMartynov/Software-Engineering-2022#86]
Student, group:  Igor Galaktionov 3530901/90203
URL:  https://github.com/igalaxy00/Converter
Git approach: gitflow

**Comment by SemenMartynov** [comment]
Мастер в релиз, это, конечно, сильно мимо.
Хорошо, что коммиты слинкованы с задачами, но стоит писать нормальные сообщения у коммитов.
И ещё разобраться с граватаром.
