### ISSUE TITLE
Money_Converter

### ISSUE THREAD

**Issue by Danil891** [SemenMartynov/Software-Engineering-2022#89]
Student, group: Danil Cherepkov 3530901/90101
URL: https://github.com/Danil891/Money_Converter
Git approach: git-flow

**Comment by SemenMartynov** [comment]
Два прямых коммита в `master` -- засквошить.

**Comment by SemenMartynov** [comment]
@Danil891 Как успехи?

**Comment by SemenMartynov** [comment]
Я сейчас вижу 4 коммита в `master` -- нужно их засквошить
https://github.com/Danil891/Money_Converter/commits/main

**Comment by Danil891** [comment]
Я не смог засквошить, постоянно выдавал ошибку, пришлось полность удалить коммиты и сбросить всё до первого

**Comment by SemenMartynov** [comment]
Тоже вполне себе рабочее решение, с точки зрения наблюдаемого результата.
