### ISSUE TITLE
Battleship Game

### ISSUE THREAD

**Issue by Slava0135** [SemenMartynov/Software-Engineering-2022#98]
Student, group: 
> Kovalevskiy V.M. / 90201

URL: 
> <https://github.com/Slava0135/nanoservice>

Git approach: 
> git-flow

**Comment by SemenMartynov** [comment]
Должен быть бейджик и для `master` и для `develop`

**Comment by Slava0135** [comment]
@SemenMartynov fixed

**Comment by SemenMartynov** [comment]
`+
