### ISSUE TITLE
XML-YAML-JSON Converter

### ISSUE THREAD

**Issue by wooffie** [SemenMartynov/Software-Engineering-2022#99]
Student, group: Burkov Egor, 3530901/90201
URL: https://github.com/wooffie/converter
Git approach: git-flow

**Comment by wooffie** [comment]
Also added docker pipeline

**Comment by SemenMartynov** [comment]
`develop` в `hotfix` мерджить не нужно, они и без этого должны нормально слиться внутри `develop`
